### ISSUE TITLE
Issues in atom for windows

### ISSUE THREAD

**Issue by vinic2k** [AtomLinter/linter-shellcheck#111]
Hi,
I'm having trouble installing it on atom text editor on my windows pc. The package was installed but it says that the package was not found in its path. No matter how many times I tried it, the error dialogue pops up.
I would really appreciate any help.
Regards,
Vineesh

**Comment by Arcanemagus** [comment]
It sounds like you need to install [shellcheck](https://github.com/koalaman/shellcheck#installing) as stated in the readme 😉.

This package is just a wrapper around it.

**Comment by nemchik** [comment]
You might look into www.chocolatey.org and use it to install shellcheck. That's how I got it to work and I didn't have to set the path in Atom.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, thanks for the pointer @nemchik 😉.
