### ISSUE TITLE
Linter runs against markdown files

### ISSUE THREAD

**Issue by alexjurkiewicz** [AtomLinter/linter-shellcheck#23]
I'm seeing this in my project's `README.md`:
![screen shot 2015-08-11 at 4 22 27 pm](https://cloud.githubusercontent.com/assets/379509/9191495/4db60044-4045-11e5-8582-382e0aa6ac48.png)

**Comment by Project0** [comment]
Strange, grammerscope is set to 'source.shell', so it should not be parsed.
Probably there is a problem on the linter API, i have seen something similar to the ruby plugin and erb template files.

**Comment by steelbrain** [comment]
Dupe of https://github.com/atom-community/linter/issues/777
it's a bug in `language-markdown`. as it's providing invalid scopes.

**Comment by alexjurkiewicz** [comment]
Ah thanks for the pointer
