### ISSUE TITLE
Backticks in markdown code blocks cause an error.

### ISSUE THREAD

**Issue by remcohaszing** [AtomLinter/linter-shellcheck#26]
Consider a markdown file containing the following content:

    Run asd.
    ```sh
    foo
    ```

    ```sh
    bar --baz
    ```

When opening this file in Atom, everything is fine.

However, when the cursor is moved inside of a code block and then saving the file, the linter reports:

> Couldn't parse this backtick expansion. [SC1073] at line 3 col 1
> Unexpected "`". Fix any mentioned problems and try again. [SC1072] at line 3 col 3

**Comment by Arcanemagus** [comment]
This is a bug with `language-gfm` not properly marking code embedded in the Markdown file as embedded (it marks them with the full scope). Marking as closed. I would recommend you try the `language-markdown` package as it is much better written.
