### ISSUE TITLE
Allow linter options.

### ISSUE THREAD

**Issue by envygeeks** [AtomLinter/linter-shellcheck#27]
Shellcheck has the ability to disable certain linters, can we please get an option to disable linters.

**Comment by steelbrain** [comment]
I would love to accept a PR for that. This repo is kinda abandoned.

**Comment by envygeeks** [comment]
I don't know much about Coffee since I write pure JS for my apps.

**Comment by steelbrain** [comment]
We're also writing our new packages in pure js, and even migrating some. It's okay if you would like to rewrite it in pure js as there's just a few lines in it's only logic file. SideNote: You might wanna bookmark [js2.coffee](http://js2.coffee).

**Comment by envygeeks** [comment]
The `js2coffee` thing will never happen but I'll look into move this to pure JS sometime this week.
