### ISSUE TITLE
Failed to spawn shellcheck

### ISSUE THREAD

**Issue by Adam-Moss** [AtomLinter/linter-shellcheck#41]
Uncaught Error: write EPIPE
/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260 Uncaught BufferedProcessError: Failed to spawn command `shellcheck`. Make sure `shellcheck` is installed and on your PATH

Failing to spawn shellcheck in OSX where shellcheck is installed to /usr/local/bin. The workaround of hardcoding the full path to the executable works fine.

For reference:

shellcheck installation:
`brew install shellcheck`

/etc/paths:
`/usr/local/bin /usr/bin /bin /usr/sbin /sbin`

path:
`/Users/user.name/.nvm/versions/node/v5.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
(node is sourced via the nvm script in my .bash_profile)

**Comment by Arcanemagus** [comment]
This is an OS X issue, not an issue with `linter-shellcheck`, marking as closed.

----

For some bizarre reason Apple decided that all applications launched through the GUI should have a blank environment. There are plans being talked about to work around this limitation within Atom here: https://github.com/atom/atom/issues/4126, and in the mean time a workaround until that is put in place is being planned in the `atom-linter` helper module here: https://github.com/AtomLinter/atom-linter/issues/62.

Until one of those workarounds for this "interesting" choice of Apple's is put in place the solution is to put the full path to `shellcheck` in the `executablePath` setting, or to always launch Atom from the terminal so it can get a real environment.
