### ISSUE TITLE
Spellcheck being run on markdown files

### ISSUE THREAD

**Issue by chdsbd** [AtomLinter/linter-shellcheck#58]
When I edit markdown files in Atom, I get warnings and errors from spellcheck such as:

> Error Tips depend on target shell and yours is unknown. Add a shebang. [SC2148] at line 1 col 1

Is it possible to configure shellcheck to not run on specific file types like markdown files?

**Comment by Arcanemagus** [comment]
This is almost certainly an issue with your `language-gfm` version, I believe the version that fixes this is  included in Atom v1.6.0. You can either use the beta version, or disable `language-gfm` and install `language-markdown` which has properly marked embedded code blocks with an embedded scope.
