### ISSUE TITLE
Error: spawn EACESS

### ISSUE THREAD

**Issue by fusion809** [AtomLinter/linter-shellcheck#64]
Hi,

On 64-bit Arch Linux (if somehow my kernel version is relevant it is 4.5.5-ck), with Atom 1.7.4, this package is giving the error:

```bash
Error: spawn EACCES
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:374:9)
    at /home/fusion809/.atom/packages/linter-shellcheck/node_modules/sb-exec/lib/index.js:15:53
    at Object.<anonymous> (/home/fusion809/.atom/packages/linter-shellcheck/node_modules/sb-exec/lib/index.js:14:18)
    at [object Generator].next (native)
    at step (/home/fusion809/.atom/packages/linter-shellcheck/node_modules/sb-exec/lib/index.js:84:191)
    at /home/fusion809/.atom/packages/linter-shellcheck/node_modules/sb-exec/lib/index.js:84:368
```

I read if relevant `ls -l /bin/bash` gives:

```bash
-rwxr-xr-x 1 root root 791304 Nov 24  2015 /bin/bash
```

I saw [issue #152](https://github.com/AtomLinter/linter-php/issues/152) on the linter-php package, which is similar to this one, and based on its answer I went to (i.e., changed directory into) `~/.atom/packages/linter-shellcheck` and ran `npm install atom-linter`, but still this error persists. 

Thanks for your time,
Brenton

**Comment by Arcanemagus** [comment]
Did you run the command as you typed above, or with the full version as specified in the linked comment?

**Comment by fusion809** [comment]
Full version? I just ran `ls -l /bin/bash`. Ah, if you mean did I run `ls -l bash` from the `/bin` folder? If so now I didn't but I have now and here is the output:

```bash
-rwxr-xr-x 1 root root 791304 Nov 24  2015 bash
```

**Comment by Arcanemagus** [comment]
I meant did you run `npm install atom-linter@~4.6.0`, or what you typed above (`npm install atom-linter`)?

**Comment by rugk** [comment]
I also experience this issue...

Basically I just put the full path into the inpput ad it works now.
However the error message is really ugly. Why not check whether the file exists and show `shellcheck not found in path <path>` or something similar?

**Comment by rugk** [comment]
Interestingly even using `~` in my path did not work...

**Comment by cuzkey** [comment]
Same issue...
i'm not even seeing the executable shellcheck on my system...i'm assuming this is the problem.

**Comment by Arcanemagus** [comment]
Marking this as closed, the original reporter hasn't responded.

@rugk Expansion of `~` is magic done in your shell, no _actual_ path contains that. A few linter providers have attempted to work around this with external libraries to varying degrees of success, but this isn't one of them.
