### ISSUE TITLE
Deprecated selector in `linter-shellcheck/styles/note.less`

### ISSUE THREAD

**Issue by molovo** [AtomLinter/linter-shellcheck#86]
In `linter-shellcheck/styles/note.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .linter-highlight.note,
.linter-highlight.note` => `atom-text-editor.editor .linter-highlight.syntax--note,
.linter-highlight.note`

* `atom-text-editor::shadow .linter-highlight.note:not(.line-number),
.linter-highlight.note:not(.line-number)` => `atom-text-editor.editor .linter-highlight.syntax--note:not(.line-number),
.linter-highlight.note:not(.line-number)`

* `atom-text-editor::shadow .linter-highlight.note .linter-gutter,
.linter-highlight.note .linter-gutter` => `atom-text-editor.editor .linter-highlight.syntax--note .linter-gutter,
.linter-highlight.note .linter-gutter`

* `atom-text-editor::shadow .linter-highlight.note .region,
.linter-highlight.note .region` => `atom-text-editor.editor .linter-highlight.syntax--note .region,
.linter-highlight.note .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by C-Bouthoorn** [comment]
This message is also showing on my system:

Atom: `1.13.0-beta1`
OS: `Linux 4.4.0-32-generic #51-Ubuntu` (Ubuntu 16.04)
Node: `v6.9.1`
npm: `v4.0.2`
apm: `v1.1.1`

**Comment by dflock** [comment]
https://github.com/atom/atom/pull/12903
