### ISSUE TITLE
shellcheck doesn't support zsh

### ISSUE THREAD

**Issue by denysdovhan** [AtomLinter/linter-shellcheck#95]
shellcheck doesn't support zsh: https://github.com/koalaman/shellcheck/issues/855#issuecomment-289221172

Unfortunately, this plugin [checks for `grammarScopes: ['source.shell']`](https://github.com/AtomLinter/linter-shellcheck/blob/master/lib/main.js#L47), which means it try to lint [`.zsh` and `.zsh-theme` files](https://github.com/atom/language-shellscript/blob/master/grammars/shell-unix-bash.cson#L7-L8) too.

Probably, there's a reason to exclude `.zsh` and `.zsh-theme` files on linting.

**Comment by lucasdf** [comment]
@Arcanemagus do you think that checking if the file extension is `.zsh` or `.zsh-theme` inside the `lint` method and returning an empty array in this case would be a good solution for this? Or is there a better way to deal with this?

**Comment by Arcanemagus** [comment]
That's the only way that I can think of, we try to avoid using the file extensions for things, but this seems like one of the cases where it would be necessary.
