### ISSUE TITLE
Shellcheck linter reports Warning as Error

### ISSUE THREAD

**Issue by juan-borla** [AtomLinter/linter-shellcheck#96]
When writing a bash script that triggers [SC2029](https://github.com/koalaman/shellcheck/wiki/SC2029), Linter returns it as error.  Command-line Shellcheck returns it as "warning".

Affected version: 1.4.4

Example Code:
ssh "user"@"server" "rm -rf \"$final_root_directory/graphics\""

Result:
Error	ShellCheck	Note that, unescaped, this expands on the client side. [SC2029]

Expected Result:
Warning	ShellCheck	Note that, unescaped, this expands on the client side. [SC2029]

**Comment by lucasdf** [comment]
This rule returns a message with type `note`, which seems to me that should be treated as a message of type `info`.
